apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
  namespace: prod
  labels:
    app: gitea
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea
  template:
    metadata:
      labels:
        app: gitea
    spec:
      serviceAccountName: gitea-sa
      containers:
        - name: gitea
          image: ${ECR_REPO_URL}:${GITEA_IMAGE_TAG}
          ports:
            - containerPort: 3000
          env:
            - name: GITEA__database__DB_TYPE
              value: postgres
            - name: GITEA__database__HOST
              value: "${GITEA_DB_ENDPOINT}"
            - name: GITEA__database__NAME
              value: gitea
            - name: GITEA__database__USER
              value: gitea_admin
            - name: GITEA__database__PASSWD
              valueFrom:
                secretKeyRef:
                  name: gitea-db-credentials
                  key: password
          volumeMounts:
            - name: gitea-secrets
              mountPath: /mnt/secrets-store
              readOnly: true
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
      volumes:
        - name: gitea-secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: gitea-db-secret
