apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: gitea
  namespace: prod
spec:
  serviceRef:
    name: gitea
    port: 3000
  targetGroupARN: ${PROD_TARGET_GROUP_ARN}
  targetType: ip
